In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
print(df.head())
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values
print(X)
print(y)
print(X.shape)

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_geography = LabelEncoder()
X[:, 1] = le_geography.fit_transform(X[:, 1])
le_gender = LabelEncoder()
X[:, 2] = le_gender.fit_transform(X[:, 2])
# ohe = OneHotEncoder(categorical_features=[1])
# X = ohe.fit_transform(X).toarray()
# # evitar trampa de variable irrrelevante ;)
# X = X[:, 1:]
print(X)
print(X.shape)
y.shape

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]
(10000, 10)


(10000,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)
print(X_test)
print(X_train.shape)
print(X_test.shape)

print(type(X_train))
# print(X_train.shape)
# print(X_test-shape)
# 1). Hold-out: Dividir data de forma random en training-test (data muy grande)
# 2). (Stratified)K-Cross-Validation: Dividir data de forma random en K particiones balanceadas, se toman k-1 para training test y la restante para (data pequeña (100 datos) - grande) - [K Random Hold-Out ]
# 3). Leave-One-Out=K-CV con K=N. [muy pocos datos]. Discutido si es mejor que K-CV HW: Bootstrapping

[[667 2 0 ... 1 0 163830.64]
 [427 1 1 ... 1 1 57098.0]
 [535 0 0 ... 1 0 185630.76]
 ...
 [738 0 1 ... 1 0 181429.87]
 [590 2 0 ... 1 1 148750.16]
 [623 1 0 ... 1 0 118855.26]]
[[597 1 0 ... 1 1 192852.67]
 [523 0 0 ... 1 0 128702.1]
 [706 2 0 ... 1 1 75732.25]
 ...
 [578 2 1 ... 1 0 141533.19]
 [650 1 1 ... 1 1 11276.48]
 [573 1 1 ... 1 0 192950.6]]
(8000, 10)
(2000, 10)
<class 'numpy.ndarray'>


In [ ]:
#es clave que uds normalicen
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #normalizacion Z
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[ 0.16958176  1.51919821 -1.09168714 ...  0.64259497 -1.03227043
   1.10643166]
 [-2.30455945  0.3131264   0.91601335 ...  0.64259497  0.9687384
  -0.74866447]
 [-1.19119591 -0.89294542 -1.09168714 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.9015152  -0.89294542  0.91601335 ...  0.64259497 -1.03227043
   1.41231994]
 [-0.62420521  1.51919821 -1.09168714 ...  0.64259497  0.9687384
   0.84432121]
 [-0.28401079  0.3131264  -1.09168714 ...  0.64259497 -1.03227043
   0.32472465]]


In [ ]:
import keras #Wrapper de tensorflow (pytorch)
# import tensorflow
from keras.models import Sequential
from keras.layers import Dense #Full-connected

#relu(z)=max(0,z)


# Crear clasificador ANN
classifier = Sequential()
# una regla de dedo gordo para determinar numero de nodos en capas ocultas (al comienzo) 
# es usar el promedio de numero de nodos de entrada y salida
classifier.add(Dense(units=6, input_dim=10, kernel_initializer='uniform', activation='relu'))
# agregar segunda capa oculta
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
# capa de salida
# en este caso usar como funcion de activacion sigmoide ya que requerimos tener probabilidades de salida
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid')) #Linear->regresion, relu->regresion (valores positivos)
# compile clasificador
# adam es una variante adaptiva de SGD
# crossentropy es la funcion de costo logaritmica de raices de Information Theory, para clasificacion binaria use 'binary_crossentropy' 
# para clasificacion multiclase use 'categorical_crossentropy'
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
classifier.fit(X_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
800/800 [==============================] - 2s 1ms/step - loss: 0.4890 - accuracy: 0.7954
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4331 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4277 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4236 - accuracy: 0.8160
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4212 - accuracy: 0.8259
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4191 - accuracy: 0.8295
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4173 - accuracy: 0.8307
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4160 - accuracy: 0.8319
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4154 - accuracy: 0.8329
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4142 - accura

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred = classifier.predict(X_train)
y_pred = (y_pred > 0.5)
print(confusion_matrix(y_train, y_pred))

[[6169  199]
 [1115  517]]


In [ ]:
(6169+517)/(6169+199+517+1115)

0.83575

In [ ]:
print(accuracy_score(y_train,y_pred))

0.83575


In [ ]:
y_predt = classifier.predict(X_test)
y_predt = (y_predt > 0.5)
print(confusion_matrix(y_test, y_predt))
print(accuracy_score(y_test,y_predt))

[[1546   49]
 [ 261  144]]
0.845
